* Evaluacion parcial 1
***
1. Estructura de carpetas (sugerida):
- /notebooks: Análisis, limpieza y transformación en Jupyter Notebook.
- /data: Dataset original y procesado.
- /src: Scripts auxiliares y funciones propias.
- /outputs: Visualizaciones, reportes generados.
- /docs: Informe técnico y documentación extra.
**
2. Informe Técnico (8-12 páginas):
- Resumen ejecutivo: Propósito y resultados clave.
- Análisis exploratorio inicial: Estadísticas descriptivas, visualizaciones y caracterización del dataset.
- Metodología de transformación: Explicación detallada de técnicas y justificaciones de cada decisión tomada.
- Resultados y validación: Evidencia de la efectividad de la limpieza y transformación, validación de integridad y calidad.
- Conclusiones y recomendaciones: Reflexión final, dificultades encontradas y sugerencias.
3. Aspectos formales del código:
- Código limpio, bien comentado y documentado (docstrings)
- Reutilización de funciones y modularidad
- Manejo de excepciones
- Uso de herramientas: Python, Jupyter, Pandas, NumPy
** Ítem II: Consideraciones para la Presentación:
Focos de observación:
- Participación activa de todos los integrantes.
- Capacidad de explicar y argumentar decisiones técnicas y metodológicas.
- Dominio conceptual y claridad en la comunicación.
- Uso efectivo de recursos visuales.
Subdirección de Diseño Instruccional
2025
4. La presentación grupal (15 minutos + 5 min preguntas) debe incluir:
- Análisis del problema y enfoque de solución: Contextualización y objetivos alcanzados.
- Demostración de código clave: Explicación y justificación de fragmentos relevantes (manipulación, limpieza, transformación, entorno,
validación de datos).
- Justificación de decisiones técnicas: Argumentos claros sobre la elección de métodos y procedimientos.
- Resultados e insights principales: Visualizaciones, hallazgos y métricas.
- Lecciones aprendidas y mejoras futuras: Reflexión sobre el proceso, dificultades y oportunidades de mejora.
Aspectos formales:
- Uso de apoyos visuales (slides, notebook, gráficos)
- Lenguaje técnico adecuado y claridad en la exposición

Se da inicio a la evaluacion 1
- las columnas que contengan nuemeros son:  
    - Establecimiento codigo (codigos de hospitales son:5 )
    -Region Codigo: 15: Región de Arica y Parinacota (XV),5: Región de Valparaíso (V),13: Región Metropolitana de Santiago (RM o XIII),9: Región de La Araucanía (IX), esto corresponde a la división politica administrativa se ordenan de norte a sur.
    - Codigos de comuna: (los codigos de las comunas son:5)
    - servicio salud codigo:(los codigos que se manejan son:5  )
    - **la latitud y la longitud se utiliza principalmente para la georreferenciación de pacientes, establecimientos y eventos media **
    - años de los cuales se estrajo la data estos son 2023,2024,2025
    - las semanas estadisticas nos dividen el año en 52 o 53 semanas numeradas facilitando la la vigilancia,comparación y seguimiento de enfermedades.
    - tenemos orden de la causas de clasificadas encalificada de la mano con Causa.
    - num total de los ingresos segun la causa
    - NumMenor1Anio,Num1a4Anios,Num5a14Anios,	Num15a64Anios,Num65oMas.
    - Fecha de atencion se debe pasar de texto a numeros
    - tambien tenemos prioridad triger lo cual las categorias son
        - c1:emergencia vital(atencion inmediata), - c2 emergencia evidente(atencion antes de los 30 min),
        - c3 urgencia mediata (atencion antes de 60 min o en su defecto reevaluar),
        - c4 urgencia mediata (atencion antes de 120 min o en su defecto reevaluar),
        - c5 menos urgencia (atencion retrasable hasta 4 horas o mas si hay pacientes c2,c4 en espera)

Columnas que son string:
- establecimiento Glosa
- Region Glosa
- Comuna Glosa
- Servicio salud Glosa
- Tipo de establecimiento
- dependencia administrativa (son: 26 valores vacios )
- nivel atencion
- tipo urgencia (son: 14 valores vacios )
- nivel complejidad
- causa
- sexo paciente (f= 2428, m= 2268,femenino=1, masculino= 1,sin dato=1, X=1,1 vacio)

columnas que son numericas:
- establecimiento codigo
- region codigo
- comuna codigo
- servicio salud codigo
- latitud (20 valores vacios )
- longitud ( son 11 valores vacios)
- años
- semana estadistica
- orden causa
- num total
- NumMenor1Anios
- Num5a14Anios
- Num15a64Anios
- Num65omas ()
- **fecha (son 18 valores vacios)**
- costo de atencion cl (son 18 valores vacios)

Continua  -> sin fin  

Discreta  -> con fin  
 - Nominales  -> sin orden
 - Ordinales  -> con orden  

 Ideal trabajr con datos extremos luego para la prueba del modelo.

In [ ]:
import pandas as pd

In [ ]:
# Importamos datos sin trabajar, separandos con ';'
NOMBRE_DATA_SET = 'urgencias_noprocesados_grupo02.csv'
df_datos_sinTrab_urgencia = pd.read_csv(NOMBRE_DATA_SET, sep=';')
df_datos_sinTrab_urgencia

FileNotFoundError: [Errno 2] No such file or directory: 'urgencias_noprocesados_grupo02.csv'

In [ ]:
df_datos_sinTrab_urgencia.head()

,EstablecimientoCodigo,EstablecimientoGlosa,RegionCodigo,RegionGlosa,ComunaCodigo,ComunaGlosa,ServicioSaludCodigo,ServicioSaludGlosa,TipoEstablecimiento,DependenciaAdministrativa,...,NumTotal,NumMenor1Anio,Num1a4Anios,Num5a14Anios,Num15a64Anios,Num65oMas,FechaAtencionTexto,SexoPaciente,PrioridadTriage,CostoAtencionCLP
0,110901,Hospital Regional de Arica Dr. Juan Noe,15,Arica y Parinacota,15101,Arica,1,Servicio de Salud Arica,Hospital,Servicio de Salud,...,201,19,21,27,87,47,02-01-2023,M,C5,85725.0
1,110901,Hospital Regional de Arica Dr. Juan Noe,15,Arica y Parinacota,15101,Arica,1,Servicio de Salud Arica,Hospital,Servicio de Salud,...,193,14,25,30,106,18,02-01-2023,M,C3,85238.0
2,110901,Hospital Regional de Arica Dr. Juan Noe,15,Arica y Parinacota,15101,Arica,1,Servicio de Salud Arica,Hospital,Servicio de Salud,...,94,18,19,23,28,6,02-01-2023,M,C3,100570.0
3,110901,Hospital Regional de Arica Dr. Juan Noe,15,Arica y Parinacota,15101,Arica,1,Servicio de Salud Arica,Hospital,Servicio de Salud,...,74,3,11,17,35,8,02-01-2023,M,C4,72941.0
4,110901,Hospital Regional de Arica Dr. Juan Noe,15,Arica y Parinacota,15101,Arica,1,Servicio de Salud Arica,Hospital,Servicio de Salud,...,132,5,5,3,61,58,02-01-2023,F,C2,114833.0

In [ ]:
df_datos_sinTrab_urgencia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4742 entries, 0 to 4741
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   EstablecimientoCodigo      4742 non-null   int64
 1   EstablecimientoGlosa       4742 non-null   object
 2   RegionCodigo               4742 non-null   int64
 3   RegionGlosa                4742 non-null   object
 4   ComunaCodigo               4742 non-null   int64
 5   ComunaGlosa                4742 non-null   object
 6   ServicioSaludCodigo        4742 non-null   int64
 7   ServicioSaludGlosa         4742 non-null   object
 8   TipoEstablecimiento        4742 non-null   object
 9   DependenciaAdministrativa  4716 non-null   object
 10  NivelAtencion              4742 non-null   object
 11  TipoUrgencia               4728 non-null   object
 12  Latitud                    4722 non-null   float64
 13  Longitud                   4731 non-null   float64
 14  NivelComplejidad           4718 non-null   object
 15  Anio                       4742 non-null   int64
 16  SemanaEstadistica          4742 non-null   int64
 17  OrdenCausa                 4742 non-null   int64
 18  Causa                      4742 non-null   object
 19  NumTotal                   4742 non-null   int64
 20  NumMenor1Anio              4742 non-null   int64
 21  Num1a4Anios                4742 non-null   int64
 22  Num5a14Anios               4742 non-null   int64
 23  Num15a64Anios              4742 non-null   int64
 24  Num65oMas                  4742 non-null   int64
 25  FechaAtencionTexto         4724 non-null   object
 26  SexoPaciente               4724 non-null   object
 27  PrioridadTriage            4724 non-null   object
 28  CostoAtencionCLP           4724 non-null   float64
dtypes: float64(3), int64(13), object(13)
memory usage: 1.0+ MB

In [ ]:
df_datos_urgencia_copia = df_datos_sinTrab_urgencia.copy()

In [ ]:
import pandas as pd

df = pd.read_csv('urgencias_noprocesados_grupo02 (1).csv')
display(df.head())

  EstablecimientoCodigo;EstablecimientoGlosa;RegionCodigo;RegionGlosa;ComunaCodigo;ComunaGlosa;ServicioSaludCodigo;ServicioSaludGlosa;TipoEstablecimiento;DependenciaAdministrativa;NivelAtencion;TipoUrgencia;Latitud;Longitud;NivelComplejidad;Anio;SemanaEstadistica;OrdenCausa;Causa;NumTotal;NumMenor1Anio;Num1a4Anios;Num5a14Anios;Num15a64Anios;Num65oMas;FechaAtencionTexto;SexoPaciente;PrioridadTriage;CostoAtencionCLP
0  110901;Hospital Regional de Arica Dr. Juan Noe...
1  110901;Hospital Regional de Arica Dr. Juan Noe...
2  110901;Hospital Regional de Arica Dr. Juan Noe...
3  110901;Hospital Regional de Arica Dr. Juan Noe...
4  110901;Hospital Regional de Arica Dr. Juan Noe...